Edetect_wav('paramFile','G:\GofMXArraySpRecs\Pc\MOTU\edetect_test_params.xlsx',...
    'tfFile','E:\Code\TF_files\HF631_140122_sig1_NI_GofMXarray1\HF631_140122_sig1_invSensit.tf',...
    'timeFile','G:\GofMXArraySpRecs\Pc\MOTU\edetect_test.xlsx',...
    'wavDir',{'G:\GofMXArraySpRecs\Pc\MOTU','G:\GofMXArraySpRecs\Gmsp\MOTU'},...
    'channel',1)

Edetect_wav('paramFile','G:\GofMXArraySpRecs\Pc\MOTU\edetect_test_params.xlsx',...
    'tfFile','E:\Code\TF_files\HF631_140122_sig1_NI_GofMXarray1\HF631_140122_sig1_invSensit.tf',...
    'timeFile','G:\GofMXArraySpRecs\Pc\MOTU\edetect_test.xlsx',...
    'wavDir','G:\GofMXArraySpRecs\Pc\MOTU',...
    'channel',1)